export const cities = [
  { id: 1, name: "Delhi" },
  { id: 2, name: "Mumbai" },
  { id: 3, name: "Bangalore" },
  { id: 4, name: "Hyderabad" },
  { id: 5, name: "Chennai" },
  { id: 6, name: "Kolkata" },
  { id: 7, name: "Pune" },
  { id: 8, name: "Ahmedabad" },
  { id: 9, name: "Jaipur" },
  { id: 10, name: "Lucknow" },
];

export const busDetails = [
  {
    id: 134324,
    type: "AC Sleeper",
    fare: 750,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
    busName: "Bharat Benz",
  },
  {
    id: 143425,
    type: " Sleeper",
    fare: 750,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
  {
    id: 898343,
    type: "Seating",
    fare: 550,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
  {
    id: 462873,
    type: "Luxery",
    fare: 1750,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
  {
    id: 472347,
    type: "Electric/ Sleeper",
    fare: 1050,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
  {
    id: 134535,
    type: "AC Sleeper + Seating",
    fare: 850,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
  {
    id: 1343324,
    type: "AC Sleeper",
    fare: 750,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
  {
    id: 423678,
    type: "AC Sleeper",
    fare: 750,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
  {
    id: 568990,
    type: "AC Sleeper",
    fare: 750,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
  {
    id: 788446,
    type: "AC Sleeper",
    fare: 990,
    availableSeats: 6,
    depatureTime: "11:30 pm",
    arrivalTime: "6:00 am",
  },
];